# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:
  - job: osx
    displayName: macOS High Sierra
    timeoutInMinutes: 360
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - script: |
          # See https://github.com/Homebrew/brew/issues/1468
          brew install --build-from-source $(Build.SourcesDirectory)/Formula/OpenModelica.rb
        displayName: 'Build OpenModelica formula'
