# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


jobs:
  - job: osx
    displayName: macOS High Sierra
    timeoutInMinutes: 360
    pool:
      vmImage: 'macOS-10.13'

    steps:
      - script: |
          # See https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=vsts&tabs=yaml#xcode
          /bin/bash -c "sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer"
          # See https://github.com/Homebrew/brew/issues/1468
          brew install --HEAD --build-from-source $(Build.SourcesDirectory)/Formula/OpenModelica.rb
          # Debug
          cat /Users/vsts/Library/Logs/Homebrew/OpenModelica/03.make
        displayName: 'Build OpenModelica formula'
      - script: |
          cat /Users/vsts/Library/Logs/Homebrew/OpenModelica/03.make
        displayName: 'Print error log'

